### ISSUE TITLE
Error after upgrade to deno v1.2.0

### ISSUE THREAD

**Issue by eestevez** [srackham/drake#10]
Hi, i am receiving error after upgrade to deno v1.2.0

I think is related to the typescript version deno v1.2.0 is using.

In some functions of std Deno changed **return new URL(url).pathname**  to **return new URL(String(url)).pathname**

I think the problem will be solved if drake change its std references from 0.59.0 to 0.61.0.

The detailed error is as follows:

Check file:///home/user/deno-api/Drakefile.ts
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@v0.59.0/path/win32.ts:917:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@v0.59.0/path/posix.ts:438:18

Found 2 errors.

**Comment by srackham** [comment]
Fixed in version 1.2.5.
