### ISSUE TITLE
Global `drake` command 

### ISSUE THREAD

**Issue by oganexon** [srackham/drake#12]
Using the drake alias isn't ideal when used with multiple projects 
```
alias drake="deno run -A Drakefile.ts"
``` 

If we could have a `drake` command to execute the script in cwd that would be very nice. 
It would search for `Drakefile.ts`. 
Something like :
```sh
$ drake --help # would run Drakefile.ts
$ drake task1
```

**Comment by srackham** [comment]
This feature used to exist. 7 months ago it was dropped: https://github.com/srackham/drake/commit/f972cd3eff19b7333db5da8fb096807b245e6101

    Drop `drake` CLI command. The additional complexity, overheads and potential confusion do not justify what is essentially just syntactic sugar.

I can't remember the specific issues that caused me to drop it. Let's keep this issue open, when I get some time I'll revisit it.

**Comment by srackham** [comment]
Here's why an executable CLI command is no longer included with Drake:

- Drake is a library for writing build scripts, it is not an application or a command.
- Combining CLI app and library results in two mechanisms with different syntaxes for running scripts. This would be confusing especially for first time and casual users.
- The library is independent of the CLI command, coupling the Drake library to a CLI command encumbers it with an unnecessary dependency.

I think that a Drake CLI command would be best implemented as a separate project. This is a fairly standard practice
(for examples see projects named like `*-cli` on npm).

**Comment by oganexon** [comment]
I don't think it's useful to create a separate project for just a few lines of code.

Here is a version that suits me, I think for advanced users it would be a real plus.
```ts
import { join } from "https://x.nest.land/std@0.70.0/path/mod.ts";
import { existsSync } from "https://x.nest.land/std@0.70.0/fs/exists.ts";
import { abort } from "https://x.nest.land/drake@1.4.1/lib/utils.ts";

/** Filenames of the default configs. */
const DEFAULT_CONFIGS = [
  "Drakefile.ts",
];

/** Get default config in cwd. */
function defaultConfig(wd: string): string | undefined {
  return DEFAULT_CONFIGS.find((path) => {
    return existsSync(join(wd, path));
  });
}

const config = defaultConfig(Deno.cwd());
if (config) {
  const process = Deno.run({
    cmd: ["deno", "run", "-A", config, ...Deno.args],
  });
  const status = await process.status();
  process.close();
  Deno.exit(status.code);
} else {
  abort("No drakefile found.");
}
```
```sh
deno install -A -n drake cli.ts 
```

**Comment by srackham** [comment]
Yours is more straightforward than my CLI. It has the same drawback as running the Drakefile directly, namely you can't display `--help` or `--version` if you don't have a Drakefile or if your Drakefile has a syntax error.

I had also included a `-f, --drakefile FILE` command-line option, it was at that point things started to get schizophrenic and I had second thoughts on the wisdom of including a CLI with the library.

**Comment by oganexon** [comment]
> 
> 
> Yours is more straightforward than my CLI. It has the same drawback as running the Drakefile directly, namely you can't display `--help` or `--version` if you don't have a Drakefile or if your Drakefile has a syntax error.
> 
The functionality I'm looking for is just to be able to run `drake` easily in all projects without having to change aliases every time

**Comment by srackham** [comment]
I must be missing something? if each project has it's own root directory containing the project's `Drakefile.ts` then you don't have to change the alias, just `cd` to the project's directory and run the alias.

**Comment by oganexon** [comment]
@srackham  In fact this does not work everywhere 
For example I use a lot of different Shells on Windows 
And the aliases are not available on all of them and it is tedious to configure it for each shell
Where an installation with deno is global and works everywhere 

On second thought, my problem is not really a problem, thank you for taking the time to help me.

**Comment by srackham** [comment]
@oganexon I'm glad I was of some help.
