### ISSUE TITLE
Using drake in CI

### ISSUE THREAD

**Issue by oganexon** [srackham/drake#13]
Hi 😀
I plan to use drake in the next versions of eggs (nest.land)
But I find it difficult to use it in CI because of several errors: 
```ts
run: started
test: started
drake error: cannot locate shell: missing SHELL environment variable
```
(This is on the ubuntu workflow, the others OS are not setup properly)
https://github.com/nestdotland/eggs/runs/1146637077

**Comment by srackham** [comment]
The Drake `sh` and `shCapture` APIs execute shell commands and rely on the SHELL environment variable to determine the shell executable path. In this case the Deno API call `Deno.env.get("SHELL")` does not return a value, hence the error.

I haven't used Github CI before and don't know why the executable environment does not include the SHELL environment variable or what the work-around would be.

**Comment by srackham** [comment]
A work-around might be that failing to find SHELL env variable we fall back on "/bin/bash" (see https://docs.gitlab.com/runner/shells/).

I really should configure Github CI testing for Drake.

**Comment by oganexon** [comment]
What if we fall back on the current shell if SHELL is not found? 
```ts
if (Deno.env.get("SHELL")) {
  // run shell 
} else {
  // run the command in the current shell 
}


```

**Comment by srackham** [comment]
The following does the trick on Ubuntu 20.04 but I haven't tried it in the Github Ubuntu VM:

```
    let shellExe = Deno.env.get("SHELL")!;
    if (!shellExe) {
      shellExe = "/bin/bash";
      if (!existsSync(shellExe)) {
        abort(
          `cannot locate shell: no SHELL environment variable or ${shellExe} executable`,
        );
      }
    }
```

**Comment by oganexon** [comment]
It works on github ubuntu, I've just tested it 👍
Strangely enough, the problem only occurs on linux. On Windows and mac everything is fine.
I just have one last suggestion, it's to use powershell on windows instead of cmd. This is closer to the linux and mac shell.

**Comment by oganexon** [comment]
@srackham congrats, Drake will soon be added to our CLI 🎉
https://github.com/nestdotland/eggs/pull/85

Feel free to join our discord server to get in touch with us and get the latest news !
https://discord.com/invite/hYUsX3H

**Comment by srackham** [comment]
That's great! I've pushed the change to Github https://github.com/srackham/drake/commit/0311eac50f87753a8c4f89fe2b2f8a20239fb090, it will be in the next Drake release.

Windows does not rely on the `SHELL` os env variable and I'm guessing that the Mac VM does have `SHELL` defined.
