### ISSUE TITLE
Request: outOfDate function should accept glob patterns

### ISSUE THREAD

**Issue by KSXGitHub** [srackham/drake#2]

**Comment by srackham** [comment]
This makes sense, although you can currently get the same functionality using the `glob` API e.g. `outOfDate("foobar.js", glob("lib/**/*.ts", "**/*.ts))`

Will probably leave it until after the 1.0 release.

**Comment by srackham** [comment]
The `outOfDate` API now throws an error if any prerequisite paths do not exist. If `prereqs`
were globbed internally then missing prerequisites would not be detected. We could confine globbing to globbed paths only and check only non-globbed paths, but this adds cognative
complexity for a feature that only saves 4 characters e.g.

    outOfDate("foobar.js", ["lib/**/*.ts", "**/*.ts"]);
    outOfDate("foobar.js", glob("lib/**/*.ts", "**/*.ts"));
