### ISSUE TITLE
sh function should not be platform dependent

### ISSUE THREAD

**Issue by KSXGitHub** [srackham/drake#3]
Currently, `sh` function behavior depends on shell interpreter the OS uses, making its behavior inconsistent.

## Proposal

Yarn uses an NPM package called `@yarnpkg/parsers` to parse bash-like syntax, a Deno library should be able to use it via Pika CDN (https://cdn.pika.dev/@yarnpkg/parsers/2.0.0-rc.10).

**Comment by srackham** [comment]
The `sh` (shell) API runs a command in the system shell, this is what it's designed to do. System shells are platform dependent so, yes, it can run platform dependent commands (it's often necessary to run platform dependent commands).

Platform independent code should be written in TypeScript.

**Comment by KSXGitHub** [comment]
`Deno.run` is pretty verbose. In order to display command output, I must at least provide `{ stdout: 'inherit', stderr: 'inherit', stdin: 'inherit' }`, and in order to exit on failed command, I must `await` status function, check its `success`, and call `Deno.exit` manually. So this is minimal:

```javascript
const cp = Deno.run({
  cmd: [/* command */],
  stdout: 'inherit',
  stderr: 'inherit',
  stdin: 'inherit',
})
const { code } = await cp.status()
if (code !== 0) Deno.exit(code)
```

I think it would be convenient to introduce a `cmd` function that makes a those things simpler. While not necessary parse a shell syntax, it should allow user to construct a shell-like dot-chain in JavaScript:

```javascript
cmd('cmd1', 'arg0', 'arg1')
  .pipe(cmd('cmd2'))
  .pipe('filename.txt')
```

**Comment by srackham** [comment]
Just use the Drake `sh` and `shCapture` APIs.

Drake is a lightweight task runner with a minimal set of orthogonal helper functions covering common use cases. Additional functionality is best left to custom code or third party libraries.
