### ISSUE TITLE
Example not working [v1.0.0-rc1]

### ISSUE THREAD

**Issue by andrewmclagan** [srackham/drake#6]
#### Versions

```bash
deno 1.0.0-rc1
v8 8.2.308
typescript 3.8.3
```
```typescript
import Drake from "https://raw.github.com/srackham/drake/v1.0.0-rc1/mod.ts";
```

#### Issue

When running the hello world example we receive the following error

```bash
deno run -A Drakefile.ts hello
```

on the Drakefile:

```typescript
import {
  desc,
  run,
  task,
} from "https://raw.github.com/srackham/drake/master/mod.ts";

desc("Minimal Drake task");
task("hello", [], function () {
  console.log("Hello World!");
});

run();
```

causes the error:

```bash
error: Uncaught Error: Import 'https://deno.land/std@v1.0.0-rc1/path/mod.ts' failed: 404 Not Found
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async processImports ($deno$/compiler/imports.ts:117:23)
    at async processImports ($deno$/compiler/imports.ts:125:7)
    at async Object.processImports ($deno$/compiler/imports.ts:125:7)
    at async compile (file:///Users/runner/runners/2.169.1/work/deno/deno/cli/js/compiler.ts:144:31)
    at async tsCompilerOnMessage (file:///Users/runner/runners/2.169.1/work/deno/deno/cli/js/compiler.ts:359:22)
    at async workerMessageRecvCallback ($deno$/runtime_worker.ts:73:9)
```

#### Solutions?

Have tried locking version to v1.0.0-rc1 and also using master. Its strange as just before running the command the dependancies are downloaded:

```bash
Download https://deno.land/std@v1.0.0-rc1/fs/mod.ts
Download https://deno.land/std@v1.0.0-rc1/path/mod.ts
Download https://raw.githubusercontent.com/srackham/drake/v1.0.0-rc1/lib/help.ts
Download https://raw.githubusercontent.com/srackham/drake/v1.0.0-rc1/lib/tasks.ts
```

**Comment by srackham** [comment]
Thanks for this report.  I've just verified the problem, but it's strange.

I had a similar issue after updating to Deno v1.0.0-rc2 two days ago, at the time I just assumed it was a temporary issue with the deno.land server so switched to fetching the Deno libs directly from Github and haven't yet reverted back to deno.lang URLS e.g.

``` typescript
import * as path from "https://raw.githubusercontent.com/denoland/deno/v1.0.0-rc2/std/path/mod.ts";
```

I verified the problem with v1.0.0-rc1 and v1.0.0-rc2 but v0.42.0 worked.

It's also strange that if I paste the failed URL into the browser it fetches and displays the code.

I then ran a simple non-Drake script:

```
import * as path from "https://deno.land/std@v1.0.0-rc1/path/mod.ts";

console.log(path.normalize(Deno.cwd()));
```

It also failed but after I switched to v1.0.0-rc2 it worked.  I switched back to 1.0.0-rc1 and it also worked!

Now I could run the Drake example:

```
PS C:\Users\srackham> deno run -A .\Drakefile.ts hello
hello started
Hello World!
hello finished (1ms)
PS C:\Users\srackham> deno --version
deno 1.0.0-rc1
v8 8.2.308
typescript 3.8.3
PS C:\Users\srackham> deno run -A .\Drakefile.ts hello
hello started
Hello World!
hello finished (2ms)
PS C:\Users\srackham> type .\Drakefile.ts
import { desc, run, task } from "https://raw.github.com/srackham/drake/v1.0.0-rc1/mod.ts";

desc("Minimal Drake task");
task("hello", [], function() {
  console.log("Hello World!");
});

run()
```

I'm not sure what the correct incantation is, I had tried a few things by this stage. Will look into it again tomorrow and I'm back on my Linux machine.

**Comment by srackham** [comment]
Here's what I think is happening.

`std/fs/copy.ts` uses the unstable `utime` API and if you import
`std/fs/mod.ts` it will import `copy.ts`. I had assumed that if you
successfully cache `std/fs/mod.ts` using the `--unstable` option then,
so long as you don't call unstable APIs (which Drake does not), from
then on use of other `std/fs/mod.ts` APIs would be fine.

It appears this is not always the case. I say "not always" because
after successfully caching without `std/fs/mod.ts` the problem goes
away.

The problem seems to be permanently fixed by avoiding `std/fs/mod.ts`
by using the individual sub-modules (thus avoiding `std/fs/copy.ts`).

I've released Drake v1.0.0-rc2 which hopefully fixes this issue.

**Comment by andrewmclagan** [comment]
Awesome! This works on our end too!

**Comment by srackham** [comment]
This may also help to explain the 404's: https://github.com/denoland/deno/issues/5267
